# Generated by Django 4.0 on 2021-12-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_ca_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ca',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ca',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ca',
            name='montant',
            field=models.FloatField(null=True),
        ),
    ]
