# Generated by Django 4.0 on 2021-12-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_ca_author_alter_ca_date_created_alter_ca_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='segment',
            field=models.CharField(choices=[('Onglerie', 'Onglerie'), ('Epilation', 'Epilation'), ('Prestations corps', 'Prestations corps'), ('Prestations visage', 'Prestations visage'), ('Maquillage', 'Maquillage')], max_length=200, null=True),
        ),
    ]
