# Generated by Django 4.0 on 2021-12-30 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0007_client_remove_ca_author_ca_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ca',
            name='client',
        ),
        migrations.AddField(
            model_name='ca',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
