# Generated by Django 4.0 on 2022-01-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ca',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_created',
        ),
        migrations.AddField(
            model_name='ca',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ca',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
