# Generated by Django 4.0 on 2022-01-07 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_ca_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ca',
            name='date',
        ),
    ]
