# Generated by Django 4.0 on 2022-01-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_ca_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='month',
            field=models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ca',
            name='year',
            field=models.CharField(choices=[('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22')], max_length=200, null=True),
        ),
    ]
